<a href="https://colab.research.google.com/github/Hee0305/PDM06/blob/main/numpy/numpy_2_array2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy
## concatenate()를 이용한 배열 결합
> [numpy 배열 합치기, concatenate 함수](https://m.blog.naver.com/PostView.nhn?blogId=qbxlvnf11&logNo=221490583222&categoryNo=0&proxyReferer=https%3A%2F%2Fwww.google.com%2F)

In [5]:
import numpy as np

In [6]:
ar1 = np.array(range(1,5)).reshape(2,2)
ar1

array([[1, 2],
       [3, 4]])

In [7]:
ar1.shape

(2, 2)

In [8]:
ar2 = np.array(range(5,11)).reshape(2,3)  # np.array(range(5,11)).reshape(-1,3)
ar2

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [9]:
ar2.shape  # 2 X 3 array

(2, 3)

In [10]:
print(ar1)
print(ar2)

[[1 2]
 [3 4]]
[[ 5  6  7]
 [ 8  9 10]]


---

## concatenate()를 이용한 배열 합치기


- concatenate(array1, array2, axis = 0)
- concatenate(array1, array2, axis = 1)
- concatenate(array1, array2, axis = None)

In [11]:
np.concatenate((ar1,ar1), axis=0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [12]:
np.concatenate((ar1,ar1,ar1), axis=0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [13]:
np.concatenate((ar1,ar1), axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [14]:
np.concatenate((ar1,ar1), axis=None)

array([1, 2, 3, 4, 1, 2, 3, 4])

### ar2에 대하여도 배열합치기를 해보시오.

In [15]:
# Your code here!
np.concatenate((ar2,ar2), axis=0)

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [16]:
np.concatenate((ar2,ar2), axis=1)

array([[ 5,  6,  7,  5,  6,  7],
       [ 8,  9, 10,  8,  9, 10]])

In [17]:
np.concatenate((ar2,ar2), axis=None)

array([ 5,  6,  7,  8,  9, 10,  5,  6,  7,  8,  9, 10])

### Error in concatenation

In [18]:
np.concatenate((ar1,ar2), axis=0) #axis=0 ; fail

ValueError: ignored

> ar1의 열의 갯수 == ar2의 열의 갯수

In [19]:
ar1.shape, ar2.shape

((2, 2), (2, 3))

In [20]:
ar2.T.shape

(3, 2)

In [21]:
np.concatenate((ar1,ar2.T), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  8],
       [ 6,  9],
       [ 7, 10]])

### concatenate(array1, array2, axis = 1)

In [22]:
np.concatenate((ar1,ar2), axis=1)

array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  8,  9, 10]])



---



---



## [복습] numpy 배열 연산: broadcasting
> [파이썬 Numpy 라이브러리 (5) Broadcasting|작성자 예비개발자](https://blog.naver.com/qbxlvnf11/221509303462)

In [23]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b   # elementwise multiplication
# [출처] 파이썬 Numpy 라이브러리 (5) Broadcasting|작성자 예비개발자


array([2., 4., 6.])

In [24]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b   # broadcasted multiplication


array([2., 4., 6.])

> 차원이 다른 두 개의 피연산자를 산술 연산할 때는 원래 연산이 불가능합니다.
하지만, 연산이 가능하도록 배열 b가 브로드캐스팅이 되어 numpy array ([2.0, 2.0, 2.0])으로 확장됩니다.

### 2차원 broadcasting

In [25]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])

b = np.array([1.0, 2.0, 3.0])

a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [26]:
(a+b).shape

(4, 3)

In [27]:
from numpy import array, newaxis
a = array([0.0, 10.0, 20.0, 30.0])
b = array([1.0, 2.0, 3.0])
#c = a + b  fail
c = a[:,newaxis] + b
c


array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [28]:
c.shape

(4, 3)

## numpy statistics
> [numpy: 기술 통계](https://datascienceschool.net/01%20python/03.04%20%EA%B8%B0%EC%88%A0%20%ED%86%B5%EA%B3%84.html)
- min(), max()
- mean(), median(), var(), std()

In [29]:
a = np.array(list(range(1,10)))
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# np.min, np.max
np.min(a),np.max(a)

(1, 9)

In [31]:
# array.min(), array.max()
a.min(), a.max()

(1, 9)

In [32]:
# mean() and median()
np.mean(a), np.median(a)

(5.0, 5.0)

In [33]:
# var(), std()
a.var(), a.std()
np.var(a), np.std(a)

(6.666666666666667, 2.581988897471611)

## 2차원 배열의 기술 통계
- axis = 0
- axis = 1

In [34]:
d2arr = np.arange(1,10).reshape(-1,3)
d2arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
d2arr.max()

9

In [36]:
d2arr.max(axis=0)

array([7, 8, 9])

In [37]:
d2arr.max(axis=1)

array([3, 6, 9])

In [38]:
print(d2arr.min(axis=None))
print(d2arr.min(axis=0))
print(d2arr.min(axis=1))

1
[1 2 3]
[1 4 7]


## [DIY: 도전과제]
- axis = None, 1, 2 에 따른 평균을 구하시오.

In [39]:
# Your code here!
print(d2arr.mean(axis=None))
print(d2arr.mean(axis=0))
print(d2arr.mean(axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]
